name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Compute Code Coverage
      run: |
        rustup component add llvm-tools-preview
        cargo llvm-cov
    - name: Checking Linting
      run: |
        rustup component add clippy
        cargo clippy
    - name: Checking Foramtting
      run: |
        rustup component add rustfmt
        cargo fmt -- --check
    - name: Conduct audit
      run: cargo audit

